name: train_model
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pip=25.0.1
  - python=3.12.6
  - pip:
      - numpy==1.26.4
      - torch==2.2.2
      - pillow==11.1.0
      - torchvision==0.17.2
      - mlflow==2.21.0
      - azureml-mlflow==1.59.0.post1
      - pandas==2.2.3
      - scikit-learn==1.6.1
      - torchmetrics==1.6.1

 