$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_model
display_name: Train Model
version: 1.0
description: Train model
type: command

inputs:
  model_path:
    type: uri_folder
  train_data:
    type: uri_folder
  val_data:
    type: uri_folder
  epochs:
    type: integer
  batch_size:
    type: integer
  learning_rate:
    type: number

outputs:
  output_model:
    type: uri_folder

code: .
environment:
  image: mcr.microsoft.com/azureml/openmpi5.0-cuda12.4-ubuntu22.04:latest
  conda_file: ./conda.yml

command: >-
  python train_model.py
  --model_path ${{inputs.model_path}}
  --train_data ${{inputs.train_data}}
  --val_data ${{inputs.val_data}}
  --epochs ${{inputs.epochs}}
  --batch_size ${{inputs.batch_size}}
  --learning_rate ${{inputs.learning_rate}}
  --output_model ${{outputs.output_model}}
  
  