name: prepare_dataset
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=19.1.7
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgfortran5=14.2.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libopenblas=0.3.29
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - ncurses=6.5
  - openssl=3.4.1
  - pandas=2.2.3
  - pip=25.0.1
  - python=3.12.6
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.1
  - python_abi=3.12
  - pytz=2024.1
  - readline=8.2
  - setuptools=75.8.2
  - six=1.17.0
  - tk=8.6.13
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - pip:
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - filelock==3.18.0
      - fonttools==4.56.0
      - fsspec==2025.3.0
      - idna==3.10
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.26.4
      - opencv-contrib-python-headless==4.11.0.86
      - packaging==24.2
      - pillow==11.1.0
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyparsing==3.2.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - scipy==1.15.2
      - seaborn==0.13.2
      - sympy==1.13.3
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchvision==0.17.2
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - ultralytics==8.3.91
      - ultralytics-thop==2.0.14
      - urllib3==2.3.0
