$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: prepare_dataset
display_name: Prepare Dataset
version: 1.0
description: Prepare dataset for training
type: command
inputs:
  input_data:
    type: uri_folder
  
outputs:
  output_data:
    type: uri_folder

code: ../modules
environment: azureml:FaceRecognition:3
command: >-
  python prepare_dataset.py
  --input_data ${{inputs.input_data}}
  --output_data ${{outputs.output_data}}