name: /Users/peterbrezovcsik/miniconda3/envs/face_recognition
channels:
  - pytorch
  - anaconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - comm=0.2.2
  - cpython=3.12.6
  - debugpy=1.8.12
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.17.0
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - ipykernel=6.29.5
  - ipython=8.32.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=19.1.7
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libopenblas=0.3.24
  - libpng=1.6.46
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libtiff=4.7.0
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - lightning-utilities=0.12.0
  - llvm-openmp=15.0.7
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - openjpeg=2.5.3
  - openssl=3.4.0
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.12.6
  - python-dateutil=2.9.0post0
  - python_abi=3.12
  - pytorch=2.5.1
  - pyyaml=6.0.2
  - pyzmq=26.2.1
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.8.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - torchaudio=2.5.1
  - torchinfo=1.8.0
  - torchmetrics=1.6.1
  - torchvision=0.20.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - alembic==1.14.1
      - annotated-types==0.7.0
      - asgiref==3.8.1
      - attrs==25.1.0
      - azure-ai-ml==1.24.0
      - azure-common==1.1.28
      - azure-core==1.32.0
      - azure-core-tracing-opentelemetry==1.0.0b11
      - azure-identity==1.19.0
      - azure-mgmt-core==1.5.0
      - azure-monitor-opentelemetry==1.6.4
      - azure-monitor-opentelemetry-exporter==1.0.0b33
      - azure-storage-blob==12.24.1
      - azure-storage-file-datalake==12.18.1
      - azure-storage-file-share==12.20.1
      - blinker==1.9.0
      - cachetools==5.5.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - contourpy==1.3.1
      - cryptography==44.0.0
      - cycler==0.12.1
      - databricks-sdk==0.43.0
      - deprecated==1.2.18
      - docker==7.1.0
      - fixedint==0.1.6
      - flask==3.1.0
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.38.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - gunicorn==23.0.0
      - importlib-metadata==8.5.0
      - isodate==0.7.2
      - itsdangerous==2.2.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - mako==1.3.9
      - markdown==3.7
      - marshmallow==3.26.1
      - matplotlib==3.10.0
      - mlflow==2.20.1
      - mlflow-skinny==2.20.1
      - msal==1.31.1
      - msal-extensions==1.2.0
      - msrest==0.7.1
      - numpy==2.1.1
      - oauthlib==3.2.2
      - opencv-python==4.11.0.86
      - opentelemetry-api==1.30.0
      - opentelemetry-instrumentation==0.51b0
      - opentelemetry-instrumentation-asgi==0.51b0
      - opentelemetry-instrumentation-dbapi==0.51b0
      - opentelemetry-instrumentation-django==0.51b0
      - opentelemetry-instrumentation-fastapi==0.51b0
      - opentelemetry-instrumentation-flask==0.51b0
      - opentelemetry-instrumentation-psycopg2==0.51b0
      - opentelemetry-instrumentation-requests==0.51b0
      - opentelemetry-instrumentation-urllib==0.51b0
      - opentelemetry-instrumentation-urllib3==0.51b0
      - opentelemetry-instrumentation-wsgi==0.51b0
      - opentelemetry-resource-detector-azure==0.1.5
      - opentelemetry-sdk==1.30.0
      - opentelemetry-semantic-conventions==0.51b0
      - opentelemetry-util-http==0.51b0
      - pandas==2.2.3
      - portalocker==2.10.1
      - protobuf==5.29.3
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydash==8.0.5
      - pyjwt==2.10.1
      - pyparsing==3.2.1
      - pytz==2025.1
      - referencing==0.36.2
      - requests-oauthlib==2.0.0
      - rpds-py==0.22.3
      - rsa==4.9
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - seaborn==0.13.2
      - smmap==5.0.2
      - sqlalchemy==2.0.38
      - sqlparse==0.5.3
      - strictyaml==1.7.3
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tqdm==4.67.1
      - tzdata==2025.1
      - ultralytics==8.3.74
      - ultralytics-thop==2.0.14
      - werkzeug==3.1.3
      - wrapt==1.17.2
