name: azureml
channels:
  - anaconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - comm=0.2.2
  - debugpy=1.8.13
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.0.2
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=19.1.7
  - libedit=3.1.20250104
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libopenblas=0.3.29
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - openssl=3.4.1
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.12.6
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.1
  - python_abi=3.12
  - pyzmq=26.3.0
  - readline=8.2
  - setuptools=75.8.2
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - pip:
      - alembic==1.15.1
      - annotated-types==0.7.0
      - anyio==4.8.0
      - asgiref==3.8.1
      - attrs==25.3.0
      - azure-ai-ml==1.26.0
      - azure-common==1.1.28
      - azure-core==1.32.0
      - azure-core-tracing-opentelemetry==1.0.0b11
      - azure-identity==1.21.0
      - azure-mgmt-core==1.5.0
      - azure-monitor-opentelemetry==1.6.5
      - azure-monitor-opentelemetry-exporter==1.0.0b35
      - azure-storage-blob==12.25.0
      - azure-storage-file-datalake==12.19.0
      - azure-storage-file-share==12.21.0
      - azureml-dataprep==5.1.6
      - azureml-dataprep-native==41.0.0
      - azureml-dataprep-rslex==2.22.5
      - azureml-fsspec==1.3.1
      - blinker==1.9.0
      - cachetools==5.5.2
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==2.2.1
      - colorama==0.4.6
      - contourpy==1.3.1
      - cryptography==44.0.2
      - cycler==0.12.1
      - databricks-sdk==0.46.0
      - deprecated==1.2.18
      - docker==7.1.0
      - fastapi==0.115.11
      - filelock==3.13.1
      - fixedint==0.1.6
      - flask==3.1.0
      - fonttools==4.56.0
      - fsspec==2023.10.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.38.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.1.1
      - gunicorn==23.0.0
      - h11==0.14.0
      - idna==3.10
      - isodate==0.7.2
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - mako==1.3.9
      - markdown==3.7
      - markupsafe==2.1.5
      - marshmallow==3.26.1
      - matplotlib==3.10.1
      - mlflow==2.21.0
      - mlflow-skinny==2.21.0
      - mpmath==1.3.0
      - msal==1.32.0
      - msal-extensions==1.3.1
      - msrest==0.7.1
      - networkx==3.3
      - oauthlib==3.2.2
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.31.0
      - opentelemetry-instrumentation==0.52b0
      - opentelemetry-instrumentation-asgi==0.52b0
      - opentelemetry-instrumentation-dbapi==0.52b0
      - opentelemetry-instrumentation-django==0.52b0
      - opentelemetry-instrumentation-fastapi==0.52b0
      - opentelemetry-instrumentation-flask==0.52b0
      - opentelemetry-instrumentation-psycopg2==0.52b0
      - opentelemetry-instrumentation-requests==0.52b0
      - opentelemetry-instrumentation-urllib==0.52b0
      - opentelemetry-instrumentation-urllib3==0.52b0
      - opentelemetry-instrumentation-wsgi==0.52b0
      - opentelemetry-resource-detector-azure==0.1.5
      - opentelemetry-sdk==1.31.0
      - opentelemetry-semantic-conventions==0.52b0
      - opentelemetry-util-http==0.52b0
      - pillow==11.0.0
      - protobuf==5.29.3
      - psutil==6.1.1
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydash==8.0.5
      - pyjwt==2.10.1
      - pyparsing==3.2.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rpds-py==0.23.1
      - rsa==4.9
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.39
      - sqlparse==0.5.3
      - starlette==0.46.1
      - strictyaml==1.7.3
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchvision==0.17.2
      - tqdm==4.67.1
      - ultralytics==8.3.91
      - ultralytics-thop==2.0.14
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
