name: test_model
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pip=25.0.1
  - python=3.12.6
  - pip:
      - torch==2.2.2
      - pillow==11.1.0
      - torchvision==0.17.2
      - mlflow==2.21.0
      - pandas==2.2.3
      - ultralytics==8.3.91
      - ultralytics-thop==2.0.14

